on: ['push', 'pull_request']

name: e2e

jobs:
  test:
    name: e2e
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn test:e2e
        run: |
            yarn install
            yarn test:e2e